const dictionary = {}
const builders = {}
require("./ack").register(dictionary);
require("./ack").registerBuilder(builders);
require("./boutstop").register(dictionary);
require("./boutstop").registerBuilder(builders);
require("./broken").register(dictionary);
require("./broken").registerBuilder(builders);
require("./deny").register(dictionary);
require("./deny").registerBuilder(builders);
require("./disp").register(dictionary);
require("./disp").registerBuilder(builders);
require("./getteam").register(dictionary);
require("./getteam").registerBuilder(builders);
require("./hello").register(dictionary);
require("./hello").registerBuilder(builders);
require("./info").register(dictionary);
require("./info").registerBuilder(builders);
require("./msg").register(dictionary);
require("./msg").registerBuilder(builders);
require("./nak").register(dictionary);
require("./nak").registerBuilder(builders);
require("./next").register(dictionary);
require("./next").registerBuilder(builders);
require("./ping").register(dictionary);
require("./ping").registerBuilder(builders);
require("./prev").register(dictionary);
require("./prev").registerBuilder(builders);
require("./replace").register(dictionary);
require("./replace").registerBuilder(builders);
require("./standby").register(dictionary);
require("./standby").registerBuilder(builders);
require("./stop").register(dictionary);
require("./stop").registerBuilder(builders);
require("./team").register(dictionary);
require("./team").registerBuilder(builders);
require("./updated").register(dictionary);
require("./updated").registerBuilder(builders);
export default dictionary;
export { builders };
